### ISSUE TITLE
Support for non tag-ed git repos.

### ISSUE THREAD

**Issue by LatisVlad** [hinteadan/H.Versioning#1]
There should be a way to get versions from commits rather than tags.

**Comment by hinteadan** [comment]
Well, there is.

I mean you do get consistent versioning even if you don't do semantic tagging, but the version number will look something like **0.0.0.42**.

See here: https://github.com/hinteadan/H.Versioning#semantic-tags

Other than this, I don't see how. Perhaps if you have some commit comment convention inside the team, but that's not a generic approach.

**Comment by hinteadan** [comment]
I will close this issue due to the previous comment.

**Comment by LatisVlad** [comment]
You could search the comments for semantic version formats. Something that respects the [standard](http://semver.org/) .
